name: rick and morty api
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code
        run: sudo apt update && sudo apt upgrade 
        
      - name: get to folder
        run: cd ./3/yamls

  deploy:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: apply yml
        run: kubectl apply -f Deployment.yaml -f Service.yaml -f Ingress.yaml
      
      - name: wait for apply
        run: sleep 30
        
      - name: Get service url 
        id: get-service-url 
        run: echo "SERVICE_URL=$(minikube service rick-morty-api-service --url)" >> $GITHUB_ENV 
    
  test: 
    needs: deploy 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Test service URL 
        run:  curl -f ${{ env.SERVICE_URL }} || exit 1
    
