name: rick and morty api

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and upgrade system
        run: ls && cd 3/yamls && pws

      - name: Update and upgrade system
        run: echo $(pwd)

      - name: Verify working directory
        run: pwd && ls -al

