name: rick and morty api

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ccheckout code
        uses: actions/checkout@v4

      - name: update and upgrade system
        run: sudo apt update && sudo apt upgrade 

  minikube-apply-test:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: apply YAMLs
        run: |
          cd /home/runner/work/rick-morty-api/rick-morty-api/3/yamls
          kubectl apply -f Deployment.yaml -f Service.yaml 
      
      - name: Wait for Minikube to be ready
        run: |
          echo "check if minikube ready..."
          until minikube ip; do
          echo "minikube not ready retrying in 5 sec..."
          sleep 5
          done
              
      - name: get service and test it
        run: |
          MINIKUBE_IP=$(minikube ip)
          NODEPORT=$(kubectl get svc rick-morty-api-service -o=jsonpath='{.spec.ports[0].nodePort}')
          SERVICE_URL="http://${MINIKUBE_IP}:${NODEPORT}"
          curl -f $SERVICE_URL || exit 1
        
