name: Rick and Morty API

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install minikube
        uses: medyagh/setup-minikube@latest

      - name: start minikube
        id: minikube
        run:  minikube start --driver=docker

      - name: wait for minikube start
        run: |
          until minikube ip &>/dev/null; do
            echo "Minikube not ready. Retrying in 5 seconds..."
            sleep 5
          done
          MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: $MINIKUBE_IP"

      - name: apply ymls
        run: |
          cd /home/runner/work/rick-morty-api/rick-morty-api/3/yamls
          kubectl apply -f Deployment.yaml -f Service.yaml

      - name: waite for deploy ymals 
        run: sleep 20 && kubectl get all
      
      - name: Get NodePort, Service URL, and test
        run: |
    
          MINIKUBE_IP=$(minikube ip)
          NODEPORT=$(kubectl get svc rick-morty-api-service -o=jsonpath='{.spec.ports[0].nodePort}')
          # Debugging: print out Minikube IP and NodePort
          echo "Minikube IP: $MINIKUBE_IP"
          echo "NodePort: $NODEPORT"
          SERVICE_URL="http://${MINIKUBE_IP}:${NODEPORT}"
          echo "Testing service URL: $SERVICE_URL"
          curl -f "$SERVICE_URL" || exit 1  
